apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: redhat-ods-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
  labels:
    name: rhods-operator
spec:
  selector:
    matchLabels:
      name: rhods-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: rhods-operator
      labels:
        name: rhods-operator
    spec:
      securityContext:
        runAsNonRoot: true
        # TODO(user): For common cases that do not require escalating privileges
        # it is recommended to ensure that all your Pods/Containers are restrictive.
        # More info: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        # Please uncomment the following code if your project does NOT have to work on old Kubernetes
        # versions < 1.19 or on vendors versions which do NOT support this field by default (i.e. Openshift < 4.11 ).
        # seccompProfile:
        #   type: RuntimeDefault
      containers:
      - command:
        - /manager
        env:
          - name: OPERATOR_NAME
            value: rhods-operator
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DEFAULT_MANIFESTS_PATH
            value: /opt/manifests
        args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=0.0.0.0:8080
          - --leader-elect
        image: controller:latest
        imagePullPolicy: Always
        name: rhods-operator
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 780Mi
      serviceAccountName: redhat-ods-operator-controller-manager
      terminationGracePeriodSeconds: 10
