apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: rhods-operator
  name: redhat-ods-operator-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/part-of: rhods-operator
status:
  loadBalancer: {}
