# permissions for end users to view awsplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsplugin-viewer-role
rules:
- apiGroups:
  - aws.plugins.kubeflow.org.my.domain
  resources:
  - awsplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.plugins.kubeflow.org.my.domain
  resources:
  - awsplugins/status
  verbs:
  - get
