# permissions for end users to edit awsplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsplugin-editor-role
rules:
- apiGroups:
  - aws.plugins.kubeflow.org.my.domain
  resources:
  - awsplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.plugins.kubeflow.org.my.domain
  resources:
  - awsplugins/status
  verbs:
  - get
