# permissions for end users to edit datascienceclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datasciencecluster-editor-role
rules:
- apiGroups:
  - datasciencecluster.opendatahub.io.opendatahub.io
  resources:
  - datascienceclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datasciencecluster.opendatahub.io.opendatahub.io
  resources:
  - datascienceclusters/status
  verbs:
  - get
