# permissions for end users to view dscinitializations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dscinitialization-viewer-role
rules:
- apiGroups:
  - dscinitialization.opendatahub.io.opendatahub.io
  resources:
  - dscinitializations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dscinitialization.opendatahub.io.opendatahub.io
  resources:
  - dscinitializations/status
  verbs:
  - get
