# permissions for end users to edit dscinitializations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dscinitialization-editor-role
rules:
- apiGroups:
  - dscinitialization.opendatahub.io.opendatahub.io
  resources:
  - dscinitializations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dscinitialization.opendatahub.io.opendatahub.io
  resources:
  - dscinitializations/status
  verbs:
  - get
