# permissions for end users to edit dscinitiatlizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dscinitiatlization-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: opendatahub-operator
    app.kubernetes.io/part-of: opendatahub-operator
    app.kubernetes.io/managed-by: kustomize
  name: dscinitiatlization-editor-role
rules:
- apiGroups:
  - dscinitialization.opendatahub.io
  resources:
  - dscinitiatlizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dscinitialization.opendatahub.io
  resources:
  - dscinitiatlizations/status
  verbs:
  - get
