# permissions for end users to view gcpplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcpplugin-viewer-role
rules:
- apiGroups:
  - gcp.plugins.kubeflow.org.my.domain
  resources:
  - gcpplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.plugins.kubeflow.org.my.domain
  resources:
  - gcpplugins/status
  verbs:
  - get
