# permissions for end users to edit kfconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kfconfig-editor-role
rules:
- apiGroups:
  - kfconfig.apps.kubeflow.org.my.domain
  resources:
  - kfconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kfconfig.apps.kubeflow.org.my.domain
  resources:
  - kfconfigs/status
  verbs:
  - get
