# permissions for end users to view kfconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kfconfig-viewer-role
rules:
- apiGroups:
  - kfconfig.apps.kubeflow.org.my.domain
  resources:
  - kfconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kfconfig.apps.kubeflow.org.my.domain
  resources:
  - kfconfigs/status
  verbs:
  - get
