# permissions for end users to edit kfdefs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kfdef-editor-role
rules:
- apiGroups:
  - kfdef.apps.kubeflow.org.my.domain
  resources:
  - kfdefs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kfdef.apps.kubeflow.org.my.domain
  resources:
  - kfdefs/status
  verbs:
  - get
