---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kfdef.apps.kubeflow.org.my.domain
  resources:
  - kfdefs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kfdef.apps.kubeflow.org.my.domain
  resources:
  - kfdefs/finalizers
  verbs:
  - update
- apiGroups:
  - kfdef.apps.kubeflow.org.my.domain
  resources:
  - kfdefs/status
  verbs:
  - get
  - patch
  - update
