---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dscinitialization.opendatahub.io
  resources:
  - dscinitiatlizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dscinitialization.opendatahub.io
  resources:
  - dscinitiatlizations/finalizers
  verbs:
  - update
- apiGroups:
  - dscinitialization.opendatahub.io
  resources:
  - dscinitiatlizations/status
  verbs:
  - get
  - patch
  - update
