# permissions for end users to edit workbenches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workbench-editor-role
rules:
- apiGroups:
  - workbench.opendatahub.io.opendatahub.io
  resources:
  - workbenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workbench.opendatahub.io.opendatahub.io
  resources:
  - workbenches/status
  verbs:
  - get
