# permissions for end users to view workbenches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workbench-viewer-role
rules:
- apiGroups:
  - workbench.opendatahub.io.opendatahub.io
  resources:
  - workbenches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workbench.opendatahub.io.opendatahub.io
  resources:
  - workbenches/status
  verbs:
  - get
