apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: opendatahub-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KfDef is the Schema for the kfdefs API
      displayName: Kf Def
      kind: KfDef
      name: kfdefs.kfdef.apps.kubeflow.org
      version: v1
  description: The Open Data Hub is a machine-learning-as-a-service platform built
    on Red Hat's Kubernetes-based OpenShift® Container Platform. Open Data Hub integrates
    multiple AI/ML open source components into one operator that can easily be downloaded
    and installed by OpenShift users.
  displayName: Open Data Hub Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - '### Components'
  links:
  - name: Opendatahub Operator
    url: https://opendatahub-operator.domain
  maturity: alpha
  provider:
    name: Open Data Hub operator allows users to install and manage components of
      the Open Data Hub. Users can mix and match tools from each project to fulfill
      the needs of their use case. Each of the
    url: projects share some components, but can be mostly seen as an extension of
      each other to provide a complete solution for both novice and skilled enterprise
      users.
  version: 0.0.0
