//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeflareController) DeepCopyInto(out *CodeflareController) {
	*out = *in
	in.Controller.DeepCopyInto(&out.Controller)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeflareController.
func (in *CodeflareController) DeepCopy() *CodeflareController {
	if in == nil {
		return nil
	}
	out := new(CodeflareController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Component) DeepCopyInto(out *Component) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Component.
func (in *Component) DeepCopy() *Component {
	if in == nil {
		return nil
	}
	out := new(Component)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Components) DeepCopyInto(out *Components) {
	*out = *in
	in.Dashboard.DeepCopyInto(&out.Dashboard)
	in.Workbenches.DeepCopyInto(&out.Workbenches)
	in.Serving.DeepCopyInto(&out.Serving)
	in.Training.DeepCopyInto(&out.Training)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Components.
func (in *Components) DeepCopy() *Components {
	if in == nil {
		return nil
	}
	out := new(Components)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Controller) DeepCopyInto(out *Controller) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Controller.
func (in *Controller) DeepCopy() *Controller {
	if in == nil {
		return nil
	}
	out := new(Controller)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dashboard) DeepCopyInto(out *Dashboard) {
	*out = *in
	out.Component = in.Component
	in.Controllers.DeepCopyInto(&out.Controllers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dashboard.
func (in *Dashboard) DeepCopy() *Dashboard {
	if in == nil {
		return nil
	}
	out := new(Dashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardController) DeepCopyInto(out *DashboardController) {
	*out = *in
	in.Controller.DeepCopyInto(&out.Controller)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardController.
func (in *DashboardController) DeepCopy() *DashboardController {
	if in == nil {
		return nil
	}
	out := new(DashboardController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardControllers) DeepCopyInto(out *DashboardControllers) {
	*out = *in
	in.DashboardController.DeepCopyInto(&out.DashboardController)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardControllers.
func (in *DashboardControllers) DeepCopy() *DashboardControllers {
	if in == nil {
		return nil
	}
	out := new(DashboardControllers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataScienceCluster) DeepCopyInto(out *DataScienceCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataScienceCluster.
func (in *DataScienceCluster) DeepCopy() *DataScienceCluster {
	if in == nil {
		return nil
	}
	out := new(DataScienceCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataScienceCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataScienceClusterList) DeepCopyInto(out *DataScienceClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataScienceCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataScienceClusterList.
func (in *DataScienceClusterList) DeepCopy() *DataScienceClusterList {
	if in == nil {
		return nil
	}
	out := new(DataScienceClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataScienceClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataScienceClusterSpec) DeepCopyInto(out *DataScienceClusterSpec) {
	*out = *in
	in.Components.DeepCopyInto(&out.Components)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataScienceClusterSpec.
func (in *DataScienceClusterSpec) DeepCopy() *DataScienceClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DataScienceClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataScienceClusterStatus) DeepCopyInto(out *DataScienceClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataScienceClusterStatus.
func (in *DataScienceClusterStatus) DeepCopy() *DataScienceClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DataScienceClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSciencePipelinesController) DeepCopyInto(out *DataSciencePipelinesController) {
	*out = *in
	in.Controller.DeepCopyInto(&out.Controller)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSciencePipelinesController.
func (in *DataSciencePipelinesController) DeepCopy() *DataSciencePipelinesController {
	if in == nil {
		return nil
	}
	out := new(DataSciencePipelinesController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KfNotebookController) DeepCopyInto(out *KfNotebookController) {
	*out = *in
	in.Controller.DeepCopyInto(&out.Controller)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KfNotebookController.
func (in *KfNotebookController) DeepCopy() *KfNotebookController {
	if in == nil {
		return nil
	}
	out := new(KfNotebookController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshController) DeepCopyInto(out *ModelMeshController) {
	*out = *in
	in.Controller.DeepCopyInto(&out.Controller)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshController.
func (in *ModelMeshController) DeepCopy() *ModelMeshController {
	if in == nil {
		return nil
	}
	out := new(ModelMeshController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookController) DeepCopyInto(out *NotebookController) {
	*out = *in
	in.Controller.DeepCopyInto(&out.Controller)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookController.
func (in *NotebookController) DeepCopy() *NotebookController {
	if in == nil {
		return nil
	}
	out := new(NotebookController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhModelController) DeepCopyInto(out *OdhModelController) {
	*out = *in
	in.Controller.DeepCopyInto(&out.Controller)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhModelController.
func (in *OdhModelController) DeepCopy() *OdhModelController {
	if in == nil {
		return nil
	}
	out := new(OdhModelController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Serving) DeepCopyInto(out *Serving) {
	*out = *in
	out.Component = in.Component
	in.Controllers.DeepCopyInto(&out.Controllers)
	in.TestConfigMap.DeepCopyInto(&out.TestConfigMap)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Serving.
func (in *Serving) DeepCopy() *Serving {
	if in == nil {
		return nil
	}
	out := new(Serving)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServingControllers) DeepCopyInto(out *ServingControllers) {
	*out = *in
	in.ModelMeshController.DeepCopyInto(&out.ModelMeshController)
	in.OdhModelController.DeepCopyInto(&out.OdhModelController)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServingControllers.
func (in *ServingControllers) DeepCopy() *ServingControllers {
	if in == nil {
		return nil
	}
	out := new(ServingControllers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Training) DeepCopyInto(out *Training) {
	*out = *in
	out.Component = in.Component
	in.Controllers.DeepCopyInto(&out.Controllers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Training.
func (in *Training) DeepCopy() *Training {
	if in == nil {
		return nil
	}
	out := new(Training)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingControllers) DeepCopyInto(out *TrainingControllers) {
	*out = *in
	in.DataSciencePipelinesController.DeepCopyInto(&out.DataSciencePipelinesController)
	in.CodeflareController.DeepCopyInto(&out.CodeflareController)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingControllers.
func (in *TrainingControllers) DeepCopy() *TrainingControllers {
	if in == nil {
		return nil
	}
	out := new(TrainingControllers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorbenchesControllers) DeepCopyInto(out *WorbenchesControllers) {
	*out = *in
	in.KfNotebookController.DeepCopyInto(&out.KfNotebookController)
	in.NotebookController.DeepCopyInto(&out.NotebookController)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorbenchesControllers.
func (in *WorbenchesControllers) DeepCopy() *WorbenchesControllers {
	if in == nil {
		return nil
	}
	out := new(WorbenchesControllers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workbenches) DeepCopyInto(out *Workbenches) {
	*out = *in
	out.Component = in.Component
	in.Controllers.DeepCopyInto(&out.Controllers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workbenches.
func (in *Workbenches) DeepCopy() *Workbenches {
	if in == nil {
		return nil
	}
	out := new(Workbenches)
	in.DeepCopyInto(out)
	return out
}
